### ISSUE TITLE
Incompatible types: pattern -> cylinder_bell_funnel

### ISSUE THREAD

**Issue by patrickfleith** [TimeEval/GutenTAG#24]
Hi, it seems that the pattern anomaly is not compatible with CBF base oscillations.

Here is my config file
```yaml
timeseries:
- name: demo
  length: 1000
  semi-supervised: true
  supervised: false
  channels: 1
  base-oscillations:
  - kind: cylinder_bell_funnel
    frequency: 2.0
    amplitude: 1.0
    variance: 0.05
  anomalies:
  - position: beginning
    length: 100
    kinds:
    - kind: pattern
      cbf_pattern_factor: 2.0
```

**Comment by CodeLionX** [comment]
Hi @patrickfleith,

Unfortunately, the error messages from our config-parser are a bit misleading. The CBF BO and pattern anomaly are indeed compatible. The issue with your config is of another nature, and twofold:

1. The BO kind is `cylinder-bell-funnel` (instead of ~cylinder_bell_funnel~).
2. The BO `cylinder-bell-funnel` does not take a `frequency` parameter.

Try with the following config:

```yaml
timeseries:
- name: demo
  length: 1000
  semi-supervised: true
  supervised: false
  base-oscillations:
  - kind: cylinder-bell-funnel
    amplitude: 1.0
    variance: 0.05
  anomalies:
  - position: beginning
    length: 100
    kinds:
    - kind: pattern
      cbf_pattern_factor: 2.0
```

---

> gutenTAG Version 1.4.0rc1
